apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels: 
        name: ssoserver-deployment
    spec:
      containers:
      - name: "{{  .Chart.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}        
        ports:
          - containerPort: 9443
        env:
          - name: MB_KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mb-keystore-password
                key: password
          - name: MB_TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mb-truststore-password
                key: password
          - name: EXTERNAL_IP_ADDR
            valueFrom:
              configMapKeyRef:
                name: ipaddr-config
                key: EXTERNAL_IP_ADDR  
          - name: IBM_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: apm-server-config
                key: ibm_apm_server_url
                optional: true
          - name: IBM_APM_KEYFILE
            valueFrom:
              secretKeyRef:
                name: apm-server-config
                key: ibm_apm_keyfile
                optional: true
          - name: IBM_APM_KEYFILE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: apm-server-config
                key: ibm_apm_keyfile_password
                optional: true
          - name: IBM_APM_INGRESS_URL
            valueFrom:
              secretKeyRef:
                name: apm-server-config
                key: ibm_apm_ingress_url
                optional: true
          - name: IBM_APM_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: apm-server-config
                key: ibm_apm_access_token
                optional: true                
        volumeMounts:
        - name: keystore
          mountPath: /etc/wlp/config/keystore
        - name: truststore
          mountPath: /etc/wlp/config/truststore
        - name: liberty-config
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/configMount
        - name: userids
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/useridMount
      volumes:
      - name: keystore
        secret:
          secretName: mb-keystore
      - name: truststore
        secret:
          secretName: mb-truststore
      - name: userids
        secret:
          secretName: liberty-userids
      - name: liberty-config
        configMap:
          name: liberty-logging-config
          items:
            - key: keystore.xml
              path: keystore.xml
            - key: logging.xml
              path: logging.xml
          optional: true

